config/routes.rb
Rails.application.routes.draw do
  get '*link/:id', to: 'sub_pages#show', constraints: SubPageConstraint, as: :sub_page_link
  get '*link', to: 'menu_entities#show', constraints: MenuEntityConstraint, as: :menu_entity_link

  resources :menu_entities
  resources :sub_pages
  resources :contacts, only: [:index, :create]
  resources :order_services, only: [:new, :create]
  mount LetterOpenerWeb::Engine, at: "/letter_opener"

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  FULL_NAME_REGEXP = /[а-яА-Я]+\s+[а-яА-Я]+\s+[а-яА-Я]+/
  validates :full_name, :phone, :email, presence: true
  validates :email, email: true
  validates :phone, phony_plausible: true
  validates :full_name, format: { with: FULL_NAME_REGEXP }

  phony_normalize :phone, default_country_code: 'RU'
end

app/models/menu_entity.rb
class MenuEntity < ApplicationRecord
  VALID_LINK_REGEX = /\A[-a-zA-Z0-9]*\z/

  validates :name, :link, :text, presence: true
  validates :link, uniqueness: true, format: { with: VALID_LINK_REGEX }

  has_many :sub_pages, dependent: :destroy
  has_and_belongs_to_many :order_services

  scope :with_subpages, -> { includes(:sub_pages).where.not(sub_pages: { id: nil }) }
  scope :ordered, -> { order :name }
end

app/models/order_service.rb
class OrderService < ApplicationRecord
  FULL_NAME_REGEXP = /[а-яА-Я]+\s+[а-яА-Я]+\s+[а-яА-Я]+/
  validates :full_name, :phone, :email, :menu_entities, presence: true
  validates :email, email: true
  validates :phone, phony_plausible: true
  validates :full_name, format: { with: FULL_NAME_REGEXP }

  phony_normalize :phone, default_country_code: 'RU'

  has_and_belongs_to_many :menu_entities
end

app/models/sub_page.rb
class SubPage < ApplicationRecord
  belongs_to :menu_entity

  validates :name, :text, :menu_entity_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contacts, only: [:index, :create]

  def index
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to contacts_path
    else
      render :index
    end
  end

  private
    def set_contacts
      @contacts = Contact.all
    end

    def contact_params
      params.require(:contact).permit(:full_name, :phone, :email)
    end
end

app/controllers/menu_entities_controller.rb
class MenuEntitiesController < ApplicationController
  before_action :set_menu_entity, only: [:edit, :update, :destroy]

  def index
    @menu_entities = MenuEntity.includes(:sub_pages).all
  end

  def show
    @menu_entity = MenuEntity.find_by_link(params[:link])
  end

  def new
    @menu_entity = MenuEntity.new
  end

  def edit
  end

  def create
    @menu_entity = MenuEntity.new(menu_entity_params)

    if @menu_entity.save
      redirect_to menu_entity_link_url(@menu_entity.link)
    else
      render :new
    end
  end

  def update
    if @menu_entity.update(menu_entity_params)
      redirect_to menu_entity_link_url(@menu_entity.link)
    else
      render :edit
    end
  end

  def destroy
    @menu_entity.destroy
    redirect_to menu_entities_url
  end

  private
    def set_menu_entity
      @menu_entity = MenuEntity.find(params[:id])
    end

    def menu_entity_params
      params.require(:menu_entity).permit(:name, :link, :text)
    end
end

app/controllers/order_services_controller.rb
class OrderServicesController < ApplicationController
  def new
    @order_service = OrderService.new
  end

  def create
    @order_service = OrderService.new(order_service_params)
    if @order_service.save
      OrderServiceMailer.notify(@order_service).deliver_later
      redirect_to new_order_service_path, notice: 'Спасибо'
    else
      render :new
    end
  end

  private
    def order_service_params
      params.require(:order_service).permit(:full_name, :phone, :email, :comment, {menu_entity_ids: []})
    end
end

app/controllers/sub_pages_controller.rb
class SubPagesController < ApplicationController
  before_action :set_sub_page, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @sub_page = SubPage.new
  end

  def edit
  end

  def create
    @sub_page = SubPage.new(sub_page_params)

    if @sub_page.save
      redirect_to sub_page_link_url(@sub_page.menu_entity.link, @sub_page.id)
    else
      render :new
    end
  end

  def update
    if @sub_page.update(sub_page_params)
      redirect_to sub_page_link_url(@sub_page.menu_entity.link, @sub_page.id)
    else
      render :edit
    end
  end

  def destroy
    @sub_page.destroy
    redirect_to menu_entities_url
  end

  private
    def set_sub_page
      @sub_page = SubPage.find(params[:id])
    end

    def sub_page_params
      params.require(:sub_page).permit(:name, :text, :menu_entity_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.haml
%h1 Заполните форму

= simple_form_for(contact) do |f|
  = f.input :full_name
  = f.input :phone
  = f.input :email
  = f.button :submit, 'Отправить'

app/views/contacts/index.html.haml
= render 'form', contact: @contact
%hr
%table.table.table-bordered.table-contacts
  %thead
    %tr
      %th= t('activerecord.attributes.contact.full_name')
      %th= t('activerecord.attributes.contact.phone')
      %th= t('activerecord.attributes.contact.email')
  %tbody
    - @contacts.each do |contact|
      %tr
        %td= contact.full_name
        %td= contact.phone
        %td= contact.email

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Digitalwand
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/menu'
    .container
      - if notice.present?
        %p.bg-success= notice
      = yield

app/views/menu_entities/_form.html.haml
= simple_form_for(@menu_entity) do |f|
  = f.input :name
  = f.input :link
  = f.input :text

  = f.button :submit

app/views/menu_entities/edit.html.haml
%h1 Редактирование

= render 'form'

app/views/menu_entities/index.html.haml
%h1 Меню

%ul
  - @menu_entities.each do |menu_entity|
    %li
      = link_to menu_entity.name, menu_entity_link_url(menu_entity.link)
      - if menu_entity.sub_pages.any?
        %ul
          - menu_entity.sub_pages.each do |sub_page|
            %li= link_to sub_page.name, sub_page_link_url(sub_page.menu_entity.link, sub_page.id)

= link_to 'Новый пункт меню', new_menu_entity_path
%br
= link_to 'Новый подпункт пункт меню', new_sub_page_path

app/views/menu_entities/new.html.haml
%h1 Новый

= render 'form'

app/views/menu_entities/show.html.haml
%h1= @menu_entity.name

= @menu_entity.text
%br
%br
= link_to 'Редактировать', edit_menu_entity_path(@menu_entity)
%br
= link_to 'Удалить', @menu_entity, :method => :delete, :data => { :confirm => 'Удалить?' }

app/views/order_services/_form.html.haml
= simple_form_for(@order_service) do |f|
  = f.input :full_name
  = f.input :phone
  = f.input :email

  = f.association :menu_entities, :as => :check_boxes, collection: MenuEntity.with_subpages.ordered

  = f.input :comment

  = f.button :submit, 'Отправить'

app/views/order_services/new.html.haml
%h1 Форма заказа услуг

= render 'form'

app/views/shared/_menu.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-9", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    #bs-example-navbar-collapse-9.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to '1) Контакты', contacts_path
        %li
          = link_to '2) Меню', menu_entities_path
        %li
          = link_to '3) Форма заказа услуг', new_order_service_path
        %li
          = link_to 'Почта', '/letter_opener', target: '_blank'

app/views/sub_pages/_form.html.haml
= simple_form_for(@sub_page) do |f|
  = f.input :name
  = f.input :text
  = f.association :menu_entity

  = f.button :submit

app/views/sub_pages/edit.html.haml
%h1 Редактировать

= render 'form'

app/views/sub_pages/new.html.haml
%h1 Новый

= render 'form'

app/views/sub_pages/show.html.haml
%h1= @sub_page.name

= @sub_page.text
%br
%br
= link_to 'Редактировать', edit_sub_page_path(@sub_page)
%br
= link_to 'Удалить', @sub_page, :method => :delete, :data => { :confirm => 'Удалить?' }

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>